-- Database Schema for Monthly Metrics
-- Target Database: Supabase / PostgreSQL

CREATE TABLE IF NOT EXISTS monthly_metrics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    record_date DATE NOT NULL UNIQUE, -- The month ending or recording date
    
    -- Revenue Stream A: Collective2
    c2_subscribers INTEGER DEFAULT 0,
    
    -- Revenue Stream B: eToro
    etoro_copiers INTEGER DEFAULT 0,
    assets_under_copy DECIMAL(15, 2) DEFAULT 0.00, -- AUC in USD
    
    -- Financials
    net_income DECIMAL(15, 2) DEFAULT 0.00, -- Combined Net Income
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: Add a comment
COMMENT ON TABLE monthly_metrics IS 'Tracks monthly KPIs towards $5,000/month Net Income goal';

-- Example query to check progress
-- SELECT record_date, net_income, (net_income / 5000.0) * 100 as progress_percent FROM monthly_metrics ORDER BY record_date DESC;
